"""empty message

Revision ID: 015c427f6153
Revises: 837f39eac5d7
Create Date: 2023-07-19 18:57:05.400541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015c427f6153'
down_revision = '837f39eac5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('op1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('op2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('op3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('op4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('correct_option', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quiz_id')
        batch_op.drop_column('correct_option')
        batch_op.drop_column('op4')
        batch_op.drop_column('op3')
        batch_op.drop_column('op2')
        batch_op.drop_column('op1')
        batch_op.drop_column('question')

    # ### end Alembic commands ###
