"""new change

Revision ID: 1aac7b889ad0
Revises: 3177777cf0d8
Create Date: 2023-07-18 19:40:58.719722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aac7b889ad0'
down_revision = '3177777cf0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_number', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['question_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('question_number')

    # ### end Alembic commands ###
