"""empty message

Revision ID: 34d6dbaf0707
Revises: dd319ceeb482
Create Date: 2023-07-17 19:16:14.754232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d6dbaf0707'
down_revision = 'dd319ceeb482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.drop_column('op4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('op4', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
