"""empty message

Revision ID: 7a33e89660a9
Revises: 1ee8d4865ee6
Create Date: 2023-07-19 19:03:23.235424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a33e89660a9'
down_revision = '1ee8d4865ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_ques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.Column('op1', sa.String(length=100), nullable=True),
    sa.Column('op2', sa.String(length=100), nullable=True),
    sa.Column('op3', sa.String(length=100), nullable=True),
    sa.Column('op4', sa.String(length=100), nullable=True),
    sa.Column('correct_option', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_ques')
    # ### end Alembic commands ###
