"""empty message

Revision ID: 837f39eac5d7
Revises: 0de8c8131c4b
Create Date: 2023-07-19 18:56:21.810937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837f39eac5d7'
down_revision = '0de8c8131c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.drop_constraint('fkop', type_='foreignkey')
        batch_op.drop_column('op3')
        batch_op.drop_column('op2')
        batch_op.drop_column('quiz_id')
        batch_op.drop_column('question')
        batch_op.drop_column('op1')
        batch_op.drop_column('op4')
        batch_op.drop_column('correct_option')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_option', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('op4', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('op1', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('question', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('quiz_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('op2', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('op3', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key('fkop', 'quiz', ['quiz_id'], ['id'])

    # ### end Alembic commands ###
