"""empty message

Revision ID: a13544e68c13
Revises: 1aac7b889ad0
Create Date: 2023-07-18 19:42:24.529868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13544e68c13'
down_revision = '1aac7b889ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('op4', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.drop_column('op4')

    # ### end Alembic commands ###
