"""empty message

Revision ID: b91480393600
Revises: c0f6b3355927
Create Date: 2023-06-30 15:52:49.476814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91480393600'
down_revision = 'c0f6b3355927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['op1'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('correct_option',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###
