"""empty message

Revision ID: b9fc7a40adc8
Revises: 7889b8571679
Create Date: 2023-07-18 19:49:19.619385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fc7a40adc8'
down_revision = '7889b8571679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.drop_column('question_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_ques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_number', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
